character:
  template: dnd
  pdf_template: dnd
  system: D&D 5e
  full_name: Taida Kibbles
  short_description: A sloth :).
  bg: /static/assets/bg/char1.jpg
  stash:
    hp: 20
    inspiration: 0
    quick_to_help: 1
    spell_slots:
      1: 3
    money:
      gp: 10
      sp: 0
      cp: 0
  spec:
    general:
      gender: Male
      age: 16
      size: 2.75
      images:
        - /static/assets/chars/taida/tmp.png
      image_credits: n/a
      home: TBD
      lore:
        bonds: TBD
        personality: |
          TBD. Draft:

          - Slow and nice
          - Gets overwhelmed quickly
          - Doesn't talk much
          - Pretty wise and smart
          - Inventor
          - When he has his power suit on, shit goes down

        backstory: TBD
    ogl:
      $ref: ogl
      current_hp: "{{ parent().parent()['stash']['hp'] }}"

      class: Artificer
      subclass: Armorer
      level: 3
      race: Folivoran, Three-Toed
      alignment: NG
      size_class: Small
      spellcasting_mod: int
      stats:
        str: 9
        dex: 7
        con: 10
        int: 16
        wis: 17  # + 1 from race
        cha: 13  # + 2 from race
      movement:
        land: 25
        climb: 25
      vision: 30
      max_hp: 20
      hit_dice: 8
      languages: ["Common", "Folivoran", "+1|str", "+2|str"]
      race_abilities:
        - >
          Quick To Help: Folivorans are ever ready to lend a close
          friend a hand. You can take the Help action as a bonus action
          a number of times equal to your Charisma modifier. You
          regain all uses when you finish a long rest.
        - >
          Heavy Sleeper: You must sleep at least 7 hours of a long
          rest and 30 minutes of a short rest that you take. After
          finishing either, you gain temporary hitpoints equal to your
          proficiency bonus. While sleeping, you have disadvantage on
          Wisdom (Perception) checks.
        - >
          Clawed Hands: Because of your claws, you have a
          climbing speed of 25 feet. In addition, your claws are natural
          weapons, which you can use to make unarmed strikes. If you
          hit with them, you deal slashing damage equal to 1d4 + your
          Strength modifier, instead of the bludgeoning damage normal
          for an unarmed strike.
        - >
          Speak With Small Beasts: Through sounds and gestures,
          you can communicate simple ideas with Small or smaller
          beasts.
        - >
          Head On A Swivel: You can turn your head almost
          completely around and are rarely caught off guard. If you are
          surprised, you can still act in the first round of combat, but
          your turn for that round comes last, regardless of your
          initiative check result.
        - >
          Extra Adorable: You have proficiency in the Persuasion
          skill.
      class_abilities:
        - |
          Magical Tinkering:
          At 1st level, you've learned how to invest a spark of magic into mundane objects.
          To use this ability, you must have thieves' tools or artisan's tools in hand.
          You then touch a Tiny nonmagical object as an action and give it one of the following magical properties
          of your choice:

          - The object sheds bright light in a 5-foot radius and dim light for an additional 5 feet.
          - Whenever tapped by a creature, the object emits a recorded message that can be heard up to 10 feet away. You utter the message when you bestow this property on the object, and the recording can be no more than 6 seconds long.
          - The object continuously emits your choice of an odor or a nonverbal sound (wind, waves, chirping, or the like). The chosen phenomenon is perceivable up to 10 feet away.
          - A static visual effect appears on one of the object's surfaces. This effect can be a picture, up to 25 words of text, lines and shapes, or a mixture of these elements, as you like.

          The chosen property lasts indefinitely. As an action, you can touch the object and end the property early.

          You can bestow magic on multiple objects, touching one object each time you use this feature, though a
          single object can only bear one property at a time. The maximum number of objects you can affect with this
          feature at one time is equal to your Intelligence modifier (minimum of one object). If you try to exceed
          your maximum, the oldest property immediately ends, and then the new property applies.
        - |
          Infuse Item:
          See rulebook.

          Chosen infusions:

          - Armor of Magical Strength.
            This armor has 6 charges. The wearer can expend the armor's charges in the following ways:
            - When the wearer makes a Strength check or a Strength saving throw, it can expend 1 charge to add a bonus to the roll equal to its Intelligence modifier.
            - If the creature would be knocked prone, it can use its reaction to expend 1 charge to avoid being knocked prone.
            The armor regains 1d6 expended charges daily at dawn.

          - Armor of Tools (UA).
            As an action, a creature wearing this infused armor can integrate into it artisan’s tools or thieves’ tools. The tools remain integrated in the armor for 8 hours or until the wearer removes the tools as an action. The armor can have only one tool integrated at a time. The wearer can add its Intelligence modifier to any ability checks it makes with the integrated tool. The wearer must have a hand free to use the tool.

          - Enhanced Defense.
            A creature gains a +1 bonus to Armor Class while wearing (armor) or wielding (shield) the infused item. The bonus increases to +2 when you reach 10th level in this class.

          - Mind Shapener.
            The infused item can send a jolt to the wearer to refocus their mind. The item has 4 charges.
            When the wearer fails a Constitution saving throw to maintain concentration on a spell, he wearer can use its reaction to expend 1 of the item's charges to succeed instead.
            The item regains 1d4 expended charges daily at dawn.
        - >
          The Right Tool for the Job:
          At 3rd level, you've learned how to produce exactly the tool you need: with thieves' tools or artisan's
          tools in hand, you can magically create one set of artisan's tools in an unoccupied space within 5
          feet of you. This creation requires 1 hour of uninterrupted work, which can coincide with a short or
          long rest. Though the product of magic, the tools are nonmagical, and they vanish when you use this
          feature again.
        - |
          Arcane Armor:
          Beginning at 3rd level, your metallurgical pursuits have led to you making armor a conduit for your magic.
          As an action, you can turn a suit of armor you are wearing into Arcane Armor, provided you have smith's tools in hand.

          You gain the following benefits while wearing this armor:

          If the armor normally has a Strength requirement, the arcane armor lacks this requirement for you.
          You can use the arcane armor as a spellcasting focus for your artificer spells.
          The armor attaches to you and can’t be removed against your will. It also expands to cover your entire body, although you can retract or deploy the helmet as a bonus action. The armor replaces any missing limbs, functioning identically to a body part it is replacing.
          The armor continues to be Arcane Armor until you don another suit of armor or you die.
        - |
          Armor Model (Guardian) - Defensive Field:
          As a bonus action, you can gain temporary hit points equal to your level in this class,
          replacing any temporary hit points you already have. You lose these temporary hit points if you doff the
          armor. You can use this bonus action a number of times equal to your proficiency bonus, and you regain all
          expended uses when you finish a long rest.
      feats: []
      inventory:
        on_hand:
          - name: A quill
          - name: A belt pouch
          - name: A small knife
          - name: A bottle of black ink
          - name: A letter from a dead colleague posing a question which you have not yet been able to answer
        stored: []
      money:
        gp: "{{ parent().parent()['stash']['money']['gp'] }}"
        sp: "{{ parent().parent()['stash']['money']['sp'] }}"
        cp: "{{ parent().parent()['stash']['money']['cp'] }}"
      spell_slots:
        1: { max: 3, available: "{{ parent().parent()['stash']['spell_slots'][1] }}" }
      known_spells: 4  # INT mod + level halfed (rounded down)
      spells: []
        # TODO
        # 1:
        #- $ref: dnd5e/spells/friends
        #  special: Via Sweet Smellls
        # + Magic Missile, Thunderwave
    dnd5e:
      $ref: dnd5e
      background: Sage
      inspiration: "{{ parent().parent()['stash']['inspiration'] }}"
      proficiency: 2
      proficiencies:
        weapons:
          simple: true
        tools: ["Thieves' tools", "Tinker's tools", "Smith's tools", "One type of artisan's tools of your choice"]
        armor:
          light: true
          medium: true
          heavy: true  # str penalty can be ignored
          shields: true
        saves:
          con: true
          int: true
      weapons:
        - name: Claws
          finese: false
          ranged: false
          wpn_type: unarmed
          dmg_type: slashing
          damage_dice: 1d4
        - name: Quarterstaff
          finese: false
          ranged: false
          wpn_type: simple
          dmg_type: bludgeoning
          damage_dice: 1d6
        - name: Sling
          finese: false
          ranged: true
          wpn_type: simple
          dmg_type: bludgeoning
          damage_dice: 1d4
          range:
            normal: 30
            better: 120
        - name: Thunder Gauntlets
          finese: false
          ranged: false
          use_int: true
          wpn_type: simple
          dmg_type: thunder
          damage_dice: 1d8
          notes: A creature hit by the gauntlet has disadvantage on attack rolls against targets other than you until the start of your next turn, as the armor magically emits a distracting pulse when the creature attacks someone else.
      armor:
        ac: 16
        name: Chain Mail
        stats: []
      skills:
        Persuasion: {proficiency: true}
        Arcana: {proficiency: true}
        History: {proficiency: true}
        Investigation: {proficiency: true}
        Perception: {proficiency: true}
    extra_counters:
      counters:
        - name: Quick to Help
          available: "{{ parent().parent()['stash']['quick_to_help'] }}"
          max: "{{ parent().parent().spec('ogl').cha_m() }}"
        - name: Infusions Known
          available: 2
        - name: Infused Items
          available: 2